version: '3.8'

services:
  kokoro-tts:
    build: .
    container_name: kokoro-tts-app-gpu
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - HF_HOME=/home/appuser/.cache/huggingface
      - TRANSFORMERS_CACHE=/home/appuser/.cache/huggingface
    volumes:
      # Optional: Mount a volume for persistent audio cache
      - ./audio_cache:/app/temp
      # Optional: Mount for model cache to avoid re-downloading
      - ./model_cache:/home/appuser/.cache
    restart: unless-stopped
    user: "1000:1000"  # Use host user ID to avoid permission issues
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 6G
          cpus: '4.0'
        reservations:
          memory: 4G
          cpus: '2.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
